### ISSUE TITLE
GroovyRuntimeException: Conflicting module versions. 

### ISSUE THREAD

**Issue by PascalSchumacher** [tkruse/gradle-groovysh-plugin#1]
Hi Thibault,

wanted to give the your plugin a try, so I added "apply plugin: 'groovysh'" to a build.gradle file.

I also added "repositories { jcenter() }" in order to fetch the plugin from bintray, but when I execute "gradle -q shell" I get:

> Plugin with id 'groovysh' not found.

What I'm I doing wrong?

**Comment by jbacker02** [comment]
Add the missing versions of Groovy appears on the console. Manually add the POM dependencies. It will resolve the issue.


		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy-all</artifactId>
			<version>2.4.16</version>
		</dependency>
		
		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy-xml</artifactId>
			<version>2.4.16</version>
		</dependency>
		
		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy</artifactId>
			<version>2.4.16</version>
		</dependency>
