### ISSUE TITLE
jline dependency not found

### ISSUE THREAD

**Issue by arteme** [tkruse/gradle-groovysh-plugin#11]
Having configured gradle-groovysh-plugin in by build.gradle as:
```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'com.tkruse.gradle:gradle-groovysh-plugin:1.0.7'
    }
}

apply plugin: 'com.github.tkruse.groovysh'
```

I get the following error:
```
$ ./gradlew  buildDevShell

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'test'.
> Could not resolve all dependencies for configuration ':buildDevShellConf'.
   > Cannot resolve external dependency jline:jline:2.11 because no repositories are defined.
     Required by:
         com.test:test:1.0-SNAPSHOT

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 25.271 secs
```

**Comment by tkruse** [comment]
the error message might be misleading. https://plugins.gradle.org/m2/ probably does not contain jline, only maven plugins

**Comment by arteme** [comment]
Added ``jcenter()`` and ``mavenCentral()`` there, but that doesn't help. The funny thing is that plugin downloading phase seems to download jline version 1.0 (BTW, I use gradle 2.2, if that is of any relevance to the question).

**Comment by tkruse** [comment]
Maybe you need plugin java as well. See Example in the README...

**Comment by tkruse** [comment]
ok, happens for me as well... I will have a look

**Comment by tkruse** [comment]
I think you need a block like ```

repositories {
	jcenter()
}
```

The plugin tries to add jline2.11 to your project's dependencies.

**Comment by tkruse** [comment]
This in addition to the `buildscript { repositories ...}`

**Comment by tkruse** [comment]
I added text to README, can I close this issue? Else I could only try to make the error message more verbose.

**Comment by arteme** [comment]
Thank you, this is exactly what I was missing!
