### ISSUE TITLE
'gradle projects' exception

### ISSUE THREAD

**Issue by codepython** [tkruse/gradle-groovysh-plugin#12]
gradle projects --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.NullPointerException
	at org.gradle.api.internal.tasks.DefaultTaskDependency.add(DefaultTaskDependency.java:114)
	at org.gradle.api.internal.AbstractTask$11.run(AbstractTask.java:323)
	at org.gradle.api.internal.tasks.TaskMutator.mutate(TaskMutator.java:37)
	at org.gradle.api.internal.AbstractTask.dependsOn(AbstractTask.java:321)

In addition , my gradle version is 2.10

**Comment by tkruse** [comment]
Hi, I am not sure this is related to my plugin. does it work when you remove the plugin?

**Comment by codepython** [comment]
Hi,
  I cloned the plugin source ,then run 'grade projects' command in the source dir ,it reported the above error .

**Comment by codepython** [comment]
If I use ./gradlew projects ,it never reports error.

**Comment by tkruse** [comment]
Hi,
I am still trying to understand how you reproduce the error. Are you doing this:
```
git clone https://github.com/tkruse/gradle-groovysh-plugin
cd gradle-groovysh-plugin/
gradle projects --stacktrace
```

The above works for me, but I am not sure if that is what you did.

Or are you trying this:

```
mkdir myproject
cd myproject
git clone https://github.com/tkruse/gradle-groovysh-plugin buildSrc
gradle projects --stacktrace
```

This also does not work for me, with another exception than yours, I can check that.

When you use gradlew, do you still use gradle 2.10? (It depends on the gradle version used to create gradlew).

**Comment by tkruse** [comment]
I fiexd a problem with groovy version in 30a9c30c0697d. Maybe you can pull, then check out the develop branch of the plugin and see if that works?

**Comment by codepython** [comment]
I operated as your first operation steps

**Comment by tkruse** [comment]
have you tried with the latest development branch, to see if the problem still exists there?
Are you sure that you are using final gradle 2.10, and not a release candidate version?

**Comment by codepython** [comment]
sorry for later reply now .
it works now.
Thanks.

**Comment by tkruse** [comment]
Thanks for the report.
