### ISSUE TITLE
Informational: Run groovysh in Gradle build context (works with Gradle 6.x and 7.x)

### ISSUE THREAD

**Issue by sandipchitale** [tkruse/gradle-groovysh-plugin#18]
Inspired by your plugin I have implemented a Gradle init script that lets one run groovysh in Gradle build context. This one works with Gradle 6.x and 7.x.

See the Gist: https://gist.github.com/sandipchitale/6f53c646ec00752d41cddcca243d76cf

The ```gradle```, ```settings```, and ```project``` object are set in the bindings.

I have also submitted a PR to the Groovylang project (which has now been merged) that allows one to launch nested ObjectBrowser windows (drilldown) using grooysh ```:inspect``` command. Nested ObjectBroswer functionality will be available in Groovy 4.0.4 and 5.0 (and 3.0.11). Once this lands up in Gradle it will make a great interactive debugging/exploration tool for Gradle build context.

Thanks again for your initial work on this.

**Comment by sandipchitale** [comment]
This informational only. Closing.

**Comment by tkruse** [comment]
Hi @sandipchitale : Thanks so much for telling me! I never though of picking this up again. Please feel free to make a PR on the README of this project if you want to have more visibility for your script, like adding a link.

**Comment by sandipchitale** [comment]
Thanks @tkruse : I have submitted a PR. Feel free to edit or move the block around.
