### ISSUE TITLE
Doesn't work with gradle 2.3

### ISSUE THREAD

**Issue by FilipMalczak** [tkruse/gradle-groovysh-plugin#7]
Even though I've added:

    plugins {
        ...
        id "com.github.tkruse.groovysh" version "1.0.5"
    }

with this gradle version:

    $ gradle -v
    
    ------------------------------------------------------------
    Gradle 2.3
    ------------------------------------------------------------
    
    Build time:   2015-02-16 05:09:33 UTC
    Build number: none
    Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274
    
    Groovy:       2.3.9
    Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
    JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
    OS:           Linux 3.16.0-34-generic amd64

I had no groovysh, or similiar tasks. It was like applying plugin did not do anything.

**Comment by tkruse** [comment]
Hi Filip,
I am so sorry that I did not reply sooner, I was travelling a lot over the last 3 months, backpacking in Asia.

I am not sure I understand your problem, adding the plugin does not do anything in itself, it just adds a task that you can then invoke by running ```gradle -q shell```.

Did that not work for you, or is the documentation unclear? DId you expect something very different?

**Comment by FilipMalczak** [comment]
Frankly, I've forgotten about it.

I've re-checked the issue and the problem doesn't occur. I suppose it was caused by some other plugin or multiproject build. I don't think that it would even be reproducable, so I suggest you close the ticket.

Sorry to bother you.
