### ISSUE TITLE
Doesn't work even if "--no-daemon" argument is specified

### ISSUE THREAD

**Issue by sunnyone** [tkruse/gradle-groovysh-plugin#8]
Just executing "./gradlew shell -q" says "Do not run with gradle daemon (use --no-daemon)", but the same message appears with "--no-daemon" argument. It seems that "--no-daemon" succeeded to prevent from running a gradle daemon according to the "jps" result, but groovysh-plugin failed to detect it.

build.gradle
```groovy
apply plugin: 'java'
apply plugin: 'com.github.tkruse.groovysh'

buildscript {
  repositories {
      jcenter()
  }

  dependencies {
      classpath 'com.tkruse.gradle:gradle-groovysh-plugin:1.0.5'
  }
}

repositories {
    jcenter()
}

dependencies {
}
```

gradle.properties
```
org.gradle.daemon=true
```

Command line output
```
$ ./gradlew --no-daemon shell -q
This is a gradle Application Shell.
You can import your application classes and act on them.
Do not run with gradle daemon (use --no-daemon).

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shell'.
> Do not run with gradle daemon (use --no-daemon).

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
$ jps
3376 Jps
$ ./gradlew -v

------------------------------------------------------------
Gradle 2.3
------------------------------------------------------------

Build time:   2015-02-16 05:09:33 UTC
Build number: none
Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274

Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Linux 3.13.0-61-generic amd64
```

**Comment by tkruse** [comment]
True, I can reproduce this. Thanks for reporting.

Currently I use the gradle Tooling API:
```
DAEMON_PROP = 'org.gradle.daemon'
project.hasProperty(DAEMON_PROP) && project.property(DAEMON_PROP) == 'true
```
So it seems the property stay true even when using ```--no-daemon```. I must research some more, maybe I have to also check the arguments do not include ```--no-daemon```.

**Comment by tkruse** [comment]
Asking here: https://discuss.gradle.org/t/check-daemon-activation-programmatically/11071

**Comment by sunnyone** [comment]
What's happen when a daemon is running? If runing a code on a daemon causes an almost harmless effect (like just an exception is thrown), it may be convenient that raising the effect intentionally and checking/recoverying it.

**Comment by tkruse** [comment]
No, sadly, when the daemon is running, keyboard input is not working anymore. So nothing works.

**Comment by tkruse** [comment]
Ok, I release 1.0.7 without blocking. Basically my check also does not work when user calls --damon. So you should be able to use with --no-daemon.

**Comment by sunnyone** [comment]
1.0.7 works (with a warning message) on my environment. Thanks.
~~~
$ ./gradlew -q --no-daemon shell
This is a gradle Application Shell.
You can import your application classes and act on them.
!!!!! WARNING: Do not run with gradle daemon, this may disable keyboard input.  (use --no-daemon). !!!!!!!!!
Groovy Shell (2.4.4, JVM: 1.8.0_60)
Type ':help' or ':h' for help.
-------------------------------------------------------------------------------
groovy:000> println("Hello, World")
Hello, World
===> null
groovy:000> 
~~~
